### ISSUE TITLE
Nosferatu html - Text Panels - (Details) links

### ISSUE THREAD

**Issue by staphon7** [oaubert/advene#72]
Hello there,  

My operating system is Arch Linux.  

Here is the output of `advene --version`:
- Advene development version release/3.12-39-g8e93ab32

How to reproduce the issue:
- Launch Advene with `./bin/advene /<path_to>/Nosfertu_v13.azp`.
- Click on the button that says "Open a comment view in the browser".
- Select "Text Panels".
- Click on one of the "(Details)" links.

Result:
- Here is the page content:

```
Error in view panel_detail interpretation: :32:6: no element found

Traceback (most recent call last):
 File "/usr/lib/python3.9/xml/sax/expatreader.py", line 217, in feed
  self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: no element found: line 32, column 6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/home/laurent/.local/src/builds/advene_git/lib/advene/model/viewable.py", line 154, in view
  context.interpret(view_source, mimetype, result)
 File "/home/laurent/.local/src/builds/advene_git/lib/advene/model/tal/context.py", line 315, in interpret
  compiler.parseTemplate (view_source)
 File "/home/laurent/.local/src/builds/advene_git/lib/simpletal/simpleTAL.py", line 1426, in parseTemplate
  self.ourParser.parse (templateFile)
 File "/usr/lib/python3.9/xml/sax/expatreader.py", line 111, in parse
  xmlreader.IncrementalParser.parse(self, source)
 File "/usr/lib/python3.9/xml/sax/xmlreader.py", line 127, in parse
  self.close()
 File "/usr/lib/python3.9/xml/sax/expatreader.py", line 240, in close
  self.feed(b"", isFinal=True)
 File "/usr/lib/python3.9/xml/sax/expatreader.py", line 221, in feed
  self._err_handler.fatalError(exc)
 File "/usr/lib/python3.9/xml/sax/handler.py", line 38, in fatalError
  raise exception
xml.sax._exceptions.SAXParseException: :32:6: no element found
```

Question:
- Do you have the same issue?

Thank you

**Comment by oaubert** [comment]
Hi. Thanks for reporting this. I have just fixed it in the git version, and the fix will be included in the next release.
